# zsh plugins

[".config/zsh/plugins/colored-man-pages.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/colored-man-pages/colored-man-pages.plugin.zsh"
refreshPeriod = "168h"

[".config/zsh/plugins/zsh-autosuggestions.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/zsh-users/zsh-autosuggestions/refs/heads/master/zsh-autosuggestions.zsh"
refreshPeriod = "168h"

[".config/zsh/plugins/zsh-syntax-highlighting"]
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
exclude = [
    "**/.editorconfig",
    "**/.gitattributes",
    "**/.github",
    "**/.gitignore",
    "**/README.*",
    "**/LICENSE*",
]

[".config/zsh/plugins/fzf-tab"]
type = "archive"
url = "https://github.com/Aloxaf/fzf-tab/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
exclude = [
    "**/.gitignore",
    "**/.editorconfig",
    "**/.github",
    "**/.cvsignore",
    "**/README.*",
    "**/LICENSE*",
]

[".config/zsh/plugins/zsh-completions/_docker"]
type = "file"
url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/docker/completions/_docker"
refreshPeriod = "168h"

# Binaries

[".local/bin/shfmt"]
type = "file"
url = {{ gitHubLatestReleaseAssetURL "mvdan/sh" (printf "shfmt_v*_%s_%s" .chezmoi.os .chezmoi.arch) | quote }}
executable = true
refreshPeriod = "168h"

# Catppuccin themes

[".config/vim/colors/catppuccin_mocha.vim"]
type = "file"
url = "https://github.com/catppuccin/vim/raw/main/colors/catppuccin_mocha.vim"
refreshPeriod = "168h"

[".config/qBittorrent/catppuccin-mocha.qbtheme"]
type = "file"
url = {{ gitHubLatestReleaseAssetURL "catppuccin/qbittorrent" "catppuccin-mocha.qbtheme" | quote }}
refreshPeriod = "168h"

[".config/alacritty/catppuccin-mocha.toml"]
type = "file"
url = "https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml"
refreshPeriod = "168h"

[".config/bat/themes/Catppuccin Mocha.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "168h"

[".config/zsh/plugins/catppuccin-fzf-mocha.sh"]
type = "file"
url = "https://github.com/catppuccin/fzf/raw/main/themes/catppuccin-fzf-mocha.sh"
refreshPeriod = "168h"

[".config/git/delta/themes/catppuccin.gitconfig"]
type = "file"
url = "https://github.com/catppuccin/delta/raw/main/catppuccin.gitconfig"
refreshPeriod = "168h"

# mpv plugins

[".config/mpv"]
type = "archive"
url = {{ gitHubLatestReleaseAssetURL "tomasklaen/uosc" "uosc.zip" | quote }}
refreshPeriod = "168h"

[".config/mpv/script-opts/uosc.conf"]
type = "file"
url = {{ gitHubLatestReleaseAssetURL "tomasklaen/uosc" "uosc.conf" | quote }}
refreshPeriod = "168h"

[".config/mpv/scripts/autoload.lua"]
type = "file"
url = "https://raw.githubusercontent.com/mpv-player/mpv/refs/heads/master/TOOLS/lua/autoload.lua"
refreshPeriod = "168h"

[".config/mpv/scripts/thumbfast.lua"]
type = "file"
url = "https://raw.githubusercontent.com/po5/thumbfast/refs/heads/master/thumbfast.lua"
refreshPeriod = "168h"
