return {
    -- "hrsh7th/nvim-cmp",
    -- version = false,
    -- event = "InsertEnter",
    -- dependencies = {
    --     "hrsh7th/cmp-nvim-lsp",
    --     "hrsh7th/cmp-buffer",
    --     "hrsh7th/cmp-path",
    --     "micangl/cmp-vimtex",
    -- },
    -- opts = function()
    --     local cmp = require("cmp")
    --     return {
    --         completion = {
    --             completeopt = "menu,menuone,preview,noselect",
    --         },
    --         mapping = cmp.mapping.preset.insert({
    --             ["<C-u>"] = cmp.mapping.scroll_docs(-4),
    --             ["<C-d>"] = cmp.mapping.scroll_docs(4),
    --             ["<CR>"] = cmp.mapping.confirm({ select = false }),
    --             ["<S-Tab>"] = cmp.mapping.select_prev_item(),
    --             ["<Tab>"] = cmp.mapping.select_next_item(),
    --             ["<C-Space>"] = cmp.mapping.complete(),
    --             ["<C-e>"] = cmp.mapping.abort(),
    --         }),
    --         sources = cmp.config.sources({
    --             { name = "nvim_lsp" },
    --             { name = "buffer" },
    --             { name = "path" },
    --             { name = "vimtex" },
    --         }),
    --         window = {
    --             completion = cmp.config.window.bordered(),
    --             documentation = cmp.config.window.bordered(),
    --         },
    --     }
    -- end,
}
