general.import = [
  "catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
padding = { y = 1, x = 1 }
dynamic_padding = true
decorations = "None"

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
size = 11.00

[terminal.shell]
program = "tmux"
