# https://github.com/89iuv/dotfiles/blob/master/zsh/starship/starship.toml
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$sudo\
$cmd_duration\
$line_break\
$character\
"""

palette = "catppuccin_mocha"
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
style_user = "lavender bold"

[hostname]
disabled = false
style = "mauve bold"
ssh_symbol = "󰖟 "

[directory]
style = "bold blue"
truncate_to_repo = false
truncation_length = 4
truncation_symbol = ".../"
read_only = " 󰌾 "

[git_branch]
style = "bold green"
symbol = "󰘬 "

[git_status]
style = "bold lavender"
format = "([$all_status$ahead_behind]($style))"

conflicted = "[=$count](bold pink) "
stashed = "[\\$$count](bold subtext0) "
deleted = "[✘$count](bold red) "
renamed = "[»$count](bold peach) "
modified = "[!$count](bold yellow) "
staged = "[+$count](bold green) "
untracked = "[?$count](bold mauve) "

ahead = "⇡${count} "
diverged = "⇡${ahead_count} ⇣${behind_count} "
behind = "⇣${count} "

[cmd_duration]
format = "took [󰔛 $duration]($style) "

[sudo]
disabled = false
style = "bold maroon"
symbol = "󰔙 root "

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](subtext1)" # For use with zsh-vi-mode

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
